# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    db_data:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - 3002:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: playsport
            MYSQL_USER: playsport
            MYSQL_PASSWORD: playsport

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - 3003:80
      environment:
        PMA_USER: playsport
        PMA_PASSWORD: playsport
